# Generated by Django 5.0 on 2024-01-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Method',
        ),
    ]
