# Generated by Django 3.2.5 on 2021-08-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='comment',
            field=models.CharField(default='Это коктейль', max_length=400),
        ),
    ]
