# Generated by Django 5.0 on 2024-01-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_cocktail_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='method',
        ),
    ]
