# Generated by Django 5.0 on 2024-01-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_cocktail_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingridient',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
