# Generated by Django 3.2.16 on 2022-10-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_auto_20221023_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
