# Generated by Django 5.2.7 on 2025-11-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0008_client_delete_clients_remove_cocktail_ingridients'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
