# Generated by Django 5.2.7 on 2026-03-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0009_bill_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
