# Generated by Django 5.0 on 2023-12-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0010_alter_cocktail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='img',
            field=models.ImageField(default='cocktails/static/cocktails/img/default.jpg', upload_to='cocktails/static/cocktails/img/'),
        ),
    ]
