# Generated by Django 5.2.7 on 2026-03-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0010_bill_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_cock',
            field=models.BooleanField(default=True),
        ),
    ]
