# Generated by Django 5.2.7 on 2026-03-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0011_bill_is_cock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
