# Generated by Django 5.0 on 2023-12-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0013_alter_cocktail_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='img',
        ),
    ]
