# Generated by Django 5.0 on 2023-12-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0017_alter_bill_cock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
