# Generated by Django 5.0 on 2023-12-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0018_alter_bill_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
